# Change baseurl before deploy
<<<<<<< HEAD
baseurl = "https://ggyuff.github.io/"
languageCode = "zh-cn"
title = "哎哟卧"
=======
baseurl = "https://demo.stack.jimmycai.com"
languageCode = "en-us"
title = "Hugo Theme Stack Starter"
>>>>>>> parent of d6f777f (1)

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5