# Configure main menu and social menu
[[main]]
  name = "首页"
  url  = "/"
  weight = 1
[[main]]
  name = "关于"
  url  = "/about/"
  weight = 2

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/CaiJimmy/hugo-theme-stack"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"
